openebs-ndm:
  enabled: true

jiva:
  enabled: true
  replicas: 1
  defaultStoragePath: "/var/openebs"
  csiController:
    driverRegistrar:
      image:
        registry: quay.mirrors.ustc.edu.cn/
    resizer:
      image:
        registry: docker.io/
        repository: longhornio/csi-resizer
    attacher:
      image:
        registry: docker.io/
        repository: longhornio/csi-attacher
        tag: v3.4.0-amd64
    provisioner:
      image:
        registry: docker.io/
        repository: longhornio/csi-provisioner
        tag: v2.1.2-amd64
    livenessprobe:
      image:
        registry: docker.io/
        repository: longhornio/livenessprobe
        tag: v2.8.0-amd64

  csiNode:
    livenessprobe:
      image:
        registry: docker.io/
        repository: longhornio/livenessprobe
        tag: v2.8.0-amd64
    driverRegistrar:
      image:
        registry: docker.io/
        repository: longhornio/csi-node-driver-registrar
