# 配置文件参考 Helm 仓库说明
# https://openebs.github.io/jiva-operator/
jiva:
  enabled: true
  replicas: 1
  image: "registry.dockermirror.com/openebs/jiva"
  defaultStoragePath: "/var/openebs"
  csiController:
    driverRegistrar:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/csi-node-driver-registrar
        tag: v2.10.0
    resizer:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/csi-resizer
        tag: v1.8.0
    attacher:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/csi-attacher
        tag: v4.3.0
    provisioner:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/csi-provisioner
        tag: v3.6.3

    livenessprobe:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/livenessprobe
        tag: v2.10.0

  csiNode:
    livenessprobe:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/livenessprobe
        tag: v2.10.0
    driverRegistrar:
      image:
        registry: k8s.mirror.nju.edu.cn/
        repository: sig-storage/csi-node-driver-registrar
        tag: v2.10.0

  jivaOperator:
    controller:
      image:
        registry: "registry.dockermirror.com/"
        repository: openebs/jiva
    replica:
      image:
        registry: "registry.dockermirror.com/"
        repository: openebs/jiva
    image:
      registry: "registry.dockermirror.com/"
      repository: openebs/jiva-operator

  jivaCSIPlugin:
    image:
      registry: "registry.dockermirror.com/"
      repository: openebs/jiva-csi
