apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-pool-cluster
  namespace: openebs
spec:
  pools:
    - nodeSelector:
        kubernetes.io/hostname: "{kubectl get node}"
      dataRaidGroups:
        - blockDevices:
            - blockDeviceName: "{kubectl get bd -A}"
      poolConfig:
        dataRaidGroupType: "stripe"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cstor-storage
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  cstorPoolCluster: cstor-pool-cluster
  # 必须小于pool的数量
  replicaCount: "3"
