apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: prometheus
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
